### ISSUE TITLE
Update i2c terminology to replace master/slave

### ISSUE THREAD

**Issue by garethhcoleman** [Seeed-Studio/Grove_Motor_Driver_TB6612FNG#5]
Hiya

I use your library in a project of mine, and I've recently decided that I'd like to remove the terms 'master' and 'slave'.

I would like to encourage you to do the same, to save me from just hacking the code, and because everyone will then benefit from more inclusive language.

I'm happy to do the work for you and submit a PR if that helps?

Kind regards

Gareth

**Comment by Pillar1989** [comment]
I'm looking forward to your PR. @garethhcoleman
